### ISSUE TITLE
Warnings in the derivation of the materials Joomla

### ISSUE THREAD

**Issue by joomline** [froala/joomla-froala-editor#1]
material joomla http://prntscr.com/6yo97i
Probably a problem with PHP 5.6.8

**Comment by Arkadiy-Sedelnikov** [comment]
F что ты выбрал в разрешенных атрибутах? Или ты настройки совсем не сохранял?

**Comment by joomline** [comment]
после сохранения предупреждения пропали.

**Comment by Arkadiy-Sedelnikov** [comment]
Понял, починим.

**Comment by stefanneculai** [comment]
Please use English. Thank you.

**Comment by Arkadiy-Sedelnikov** [comment]
016412e4848ef61db322054fbc19988cb3b9388f
