### ISSUE TITLE
Upload files to the editor

### ISSUE THREAD

**Issue by proweb** [froala/joomla-froala-editor#2]
An error when trying to load
- Linux (Ubuntu 14.04)
- PHP 5.5.9
- Apache / 2.4.7
- Joomla! 3.4.1 Stable [Ember] 21-March-2015 20:30 GMT
- The rights of the folder are normal

![_415](https://cloud.githubusercontent.com/assets/680073/7344887/84c71426-ecd8-11e4-80f8-c65a8b4a2e35.png)

**Comment by stefanneculai** [comment]
Please use English. Thank you.

**Comment by proweb** [comment]
ОК, thanks for correction =)

**Comment by Arkadiy-Sedelnikov** [comment]
not confirmed
