### ISSUE TITLE
Editing styles in edit mode code

### ISSUE THREAD

**Issue by joomline** [froala/joomla-froala-editor#8]
If you change styles and save the code in edit mode, the changes are not saved.
example:
```
<p align="justify" style="text-align: left;">text.</p>
```

**Comment by Arkadiy-Sedelnikov** [comment]
Try to insert in the settings of permitted tag attributes
Попробуй вставить в настройки разрешенные атрибуты тэгов

**Comment by joomline** [comment]
баг компонента стороннего
